import { useMemo } from 'react'
import logoSrc from '@/assets/images/logo.png'
import type {
  ChatMessage,
  HealthReport,
  Prediction,
  Source,
} from '@/types/analysis'

interface ReportPrintViewProps {
  prediction: Prediction
  report: HealthReport
  imageUrl?: string | null
  messages?: ChatMessage[]
}

function collectUniqueSources(messages: ChatMessage[] | undefined): Source[] {
  if (!messages) return []
  const seen = new Map<string, Source>()
  for (const message of messages) {
    for (const source of message.sources ?? []) {
      if (!seen.has(source.id)) seen.set(source.id, source)
    }
  }
  return [...seen.values()]
}

/**
 * Print-only report layout. Hidden on screen (`.print-only` is
 * `display: none` until @media print, see index.css) and rendered
 * alongside the interactive view so "Download PDF" can simply call
 * window.print() — the browser's print-to-PDF handles the rest.
 */
export function ReportPrintView({
  prediction,
  report,
  imageUrl,
  messages,
}: ReportPrintViewProps) {
  const sources = useMemo(() => collectUniqueSources(messages), [messages])
  const confidencePercent = Math.round(prediction.confidence * 100)

  return (
    <div className="print-only">
      <header className="mb-6 flex items-center justify-between border-b border-black pb-4">
        <div className="flex items-center gap-2">
          <img src={logoSrc} alt="LeafMind" className="h-8 w-8" />
          <span className="text-lg font-bold">LeafMind</span>
        </div>
        <div className="text-right text-xs text-neutral-600">
          <p>Medicinal Plant Identification Report</p>
          <p>Generated {new Date().toLocaleString()}</p>
        </div>
      </header>

      {imageUrl ? (
        <img
          src={imageUrl}
          alt={prediction.plantName}
          className="mb-4 max-h-64 w-full object-contain"
        />
      ) : null}

      <section className="mb-6">
        <h1 className="text-2xl font-bold">{prediction.plantName}</h1>
        <p className="text-base text-neutral-700 italic">
          {prediction.scientificName}
        </p>
        <dl className="mt-3 grid grid-cols-2 gap-2 text-sm">
          <div>
            <dt className="text-neutral-600">Confidence</dt>
            <dd className="font-semibold">{confidencePercent}%</dd>
          </div>
          <div>
            <dt className="text-neutral-600">Model version</dt>
            <dd className="font-semibold">{prediction.modelVersion}</dd>
          </div>
          <div>
            <dt className="text-neutral-600">Predicted</dt>
            <dd className="font-semibold">
              {new Date(prediction.predictedAt).toLocaleString()}
            </dd>
          </div>
        </dl>
      </section>

      <section className="mb-6">
        <h2 className="mb-2 text-lg font-bold">Summary</h2>
        <p className="text-sm leading-relaxed">{report.summary}</p>
      </section>

      <section className="mb-6 grid grid-cols-2 gap-4 text-sm">
        <div>
          <h3 className="font-semibold">Family</h3>
          <p>{report.family}</p>
        </div>
        <div>
          <h3 className="font-semibold">Native region</h3>
          <p>{report.nativeRegion}</p>
        </div>
        <div className="col-span-2">
          <h3 className="font-semibold">Growth habit</h3>
          <p>{report.growthHabit}</p>
        </div>
      </section>

      <section className="mb-6">
        <h3 className="mb-1 font-semibold">Traditional medicinal uses</h3>
        <p className="text-sm">{report.medicinalUses.join(', ')}</p>
      </section>

      <section className="mb-6">
        <h3 className="mb-1 font-semibold">Active compounds</h3>
        <p className="text-sm">{report.activeCompounds.join(', ')}</p>
      </section>

      <section className="mb-6 border border-black p-3">
        <h3 className="mb-1 font-semibold">Toxicity &amp; safety notes</h3>
        <p className="text-sm">{report.toxicityNotes}</p>
      </section>

      {sources.length > 0 ? (
        <section className="mb-6">
          <h2 className="mb-2 text-lg font-bold">Source references</h2>
          <ol className="list-decimal space-y-1 pl-5 text-sm">
            {sources.map((source) => (
              <li key={source.id}>
                {source.documentTitle}, {source.chapter} (p. {source.pageNumber}
                ) &mdash; {Math.round(source.retrievalConfidence * 100)}%
                retrieval confidence
              </li>
            ))}
          </ol>
        </section>
      ) : null}

      <footer className="mt-8 border-t border-black pt-3 text-xs text-neutral-600">
        <p>
          This report is generated by an AI system and is intended for research
          and informational purposes only. It is not a substitute for
          professional medical or botanical advice.
        </p>
      </footer>
    </div>
  )
}
