export const ROUTES = {
  home: '/',
  login: '/login',
  signup: '/signup',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  sessionExpired: '/session-expired',
  unauthorized: '/unauthorized',
  dashboard: '/dashboard',
  history: '/history',
  savedReports: '/saved-reports',
  chatHistory: '/chat-history',
  user: '/user',
  developer: '/developer',
  admin: '/admin',
  settings: '/settings',
  notFound: '*',
} as const
