import { useQuery } from '@tanstack/react-query'
import { analysisService } from '@/services/analysis.service'

/**
 * Suggested follow-up questions generated by the backend right after a
 * prediction, tailored to the identified plant.
 */
export function useFollowUpQuestions(predictionId: string) {
  return useQuery({
    queryKey: ['analysis', 'follow-ups', predictionId],
    queryFn: async () => {
      const { data } = await analysisService.getFollowUpQuestions(predictionId)
      return data
    },
    enabled: !!predictionId,
    staleTime: Infinity,
  })
}
